### ISSUE TITLE
Bar not showed properly on "modal"  presented viewcontrollers.

### ISSUE THREAD

**Issue by jvelascovanadis** [stonesam92/SSSnackbar#1]
I've found this issue trying to show the sssnackBar in a navigationViewController showed modally. After some research I've found that maybe it is happening when trying to get the superview in the show () method. 

I've replace your:
"...
UIView *superview = [UIApplication sharedApplication].delegate.window.rootViewController.view;

..."

With this:  

"...

UIViewController *topController = [UIApplication sharedApplication].keyWindow.rootViewController;

```
while (topController.presentedViewController) {
    topController = topController.presentedViewController;
}

superview = topController.view;
```

..."

And it seems to work.

**Comment by adamjack** [comment]
I've been experiencing the same issue. Thanks for the patch.

**Comment by stonesam92** [comment]
Cheers guys, fixed this now.
