### ISSUE TITLE
Snackbar is hidden by iOS keyboard. So using it for validation is tricky.

### ISSUE THREAD

**Issue by firescript** [stonesam92/SSSnackbar#6]
If we could set a position property, to maybe say bottom, or top. That would be useful. Just in cases where developers are using it to handle validation alerts. We are using it as a cocoa pod in a NativeScript plugin: https://github.com/bradmartin/nativescript-snackbar

Would it be tricky to add that ability in to the SSSnackbar?

**Comment by raulastu** [comment]
Will there be support for top?

**Comment by firescript** [comment]
@raulastu I submitted a PR giving SSSnackbar the ability to show on top or bottom.

https://github.com/stonesam92/SSSnackbar/pull/7
